{
    "openapi": "3.0.0",
    "info": {
        "title": "Tha Network | APIs",
        "version": "1.0"
    },
    "components": {
        "securitySchemes": {
            "bearerAuth": {
                "type": "http",
                "scheme": "bearer",
                "bearerFormat": "JWT"
            }
        }
    },
    "servers": [
        {
            "url": "http://tha-network.test/api",
            "description": "Local"
        },
        {
            "url": "http://service.demowebsitelinks.com:3045/api",
            "description": "Staging"
        },
        {
            "url": "https://thanetwork.org/api",
            "description": "Live"
        }
    ],
    "paths": {
        "/login": {
            "post": {
                "tags": [
                    "Auth"
                ],
                "requestBody": {
                    "description": "Your request body description",
                    "required": true,
                    "content": {
                        "application/json": {
                            "example": {
                                "email": "asd444@mailinator.com",
                                "username": "zywigodor",
                                "password": "admin!@#"
                            }
                        }
                    }
                },
                "responses": {
                    "default": {
                        "description": "Generic response"
                    }
                }
            }
        },
        "/register": {
            "post": {
                "tags": [
                    "Auth"
                ],
                "requestBody": {
                    "description": "Your request body description",
                    "required": true,
                    "content": {
                        "application/json": {
                            "example": {
                                "invitation_code": "2277490383",
                                "stripe_charge_object": "{...}",
                                "stripe_customer_id": "cus_123123123",
                                "stripe_checkout_session_id": "sub_1NfUeOKWX6MBBv9PH1iKh7KX",
                                "first_name": "Cedric",
                                "last_name": "Maya",
                                "gender": " 'Male' OR 'Female' ",
                                "phone": "1234567890",
                                "username": "asd444",
                                "email": "asd444@mailinator.com",
                                "password": "admin!@#2A",
                                "password_confirmation": "admin!@#2A",
                                "social_security_number": "1234567890"
                            }
                        }
                    }
                },
                "responses": {
                    "default": {
                        "description": "Generic response"
                    }
                }
            }
        },
        "/logout": {
            "post": {
                "tags": [
                    "Auth"
                ],
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "responses": {
                    "default": {
                        "description": "Generic response"
                    }
                }
            }
        },
        "/get-invitation-code": {
            "post": {
                "tags": [
                    "Auth"
                ],
                "requestBody": {
                    "description": "Your request body description",
                    "required": true,
                    "content": {
                        "application/json": {
                            "example": {
                                "email": "asd448@mailinator.com"
                            }
                        }
                    }
                },
                "responses": {
                    "default": {
                        "description": "Generic response"
                    }
                }
            }
        },
        "/verify-invitation-code": {
            "post": {
                "tags": [
                    "Auth"
                ],
                "requestBody": {
                    "description": "Your request body description",
                    "required": true,
                    "content": {
                        "application/json": {
                            "example": {
                                "invitation_code": "2277490383"
                            }
                        }
                    }
                },
                "responses": {
                    "default": {
                        "description": "Generic response"
                    }
                }
            }
        },
        "/forgot-password": {
            "post": {
                "tags": [
                    "Auth"
                ],
                "requestBody": {
                    "description": "Your request body description",
                    "required": true,
                    "content": {
                        "application/json": {
                            "example": {
                                "email": "asd444@mailinator.com"
                            }
                        }
                    }
                },
                "responses": {
                    "default": {
                        "description": "Generic response"
                    }
                }
            }
        },
        "/subscribe": {
            "post": {
                "tags": [
                    "Payments"
                ],
                "requestBody": {
                    "description": "Your request body description",
                    "required": true,
                    "content": {
                        "application/json": {
                            "example": {
                                "card_number": "4242424242424242",
                                "exp_month": "12",
                                "exp_year": "24",
                                "cvc": "123",
                                "token_id": "t_1231312321312321"
                            }
                        }
                    }
                },
                "responses": {
                    "default": {
                        "description": "Generic response"
                    }
                }
            }
        },
        "/me": {
            "get": {
                "tags": [
                    "Profile"
                ],
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "responses": {
                    "default": {
                        "description": "Generic response"
                    }
                }
            }
        },
        "/send-invitation": {
            "post": {
                "tags": [
                    "Auth"
                ],
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "requestBody": {
                    "description": "Your request body description",
                    "required": true,
                    "content": {
                        "application/json": {
                            "example": {
                                "emails": [
                                    "asd301@mailinator.com",
                                    "asd302@mailinator.com",
                                    "asd303@mailinator.com",
                                    "asd304@mailinator.com"
                                ]
                            }
                        }
                    }
                },
                "responses": {
                    "default": {
                        "description": "Generic response"
                    }
                }
            }
        },
        "/get-weekly-goals": {
            "get": {
                "tags": [
                    "Auth"
                ],
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "responses": {
                    "default": {
                        "description": "Generic response"
                    }
                }
            }
        },
        "/new-members-this-week": {
            "get": {
                "tags": [
                    "Auth"
                ],
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "responses": {
                    "default": {
                        "description": "Generic response"
                    }
                }
            }
        },
        "/update-profile": {
            "post": {
                "tags": [
                    "Profile"
                ],
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "requestBody": {
                    "description": "Your request body description",
                    "required": true,
                    "content": {
                        "application/json": {
                            "example": {
                                "bio" : ".....",
                                "marital_status": "[ 'married' OR 'single' ]",
                                "gender" :  "[ 'Male' OR 'Female' ]",
                                "first_name": "John",
                                "last_name" :  "Doe",
                                "phone": "1234",
                                "email" :  "jdoe@maillinator.com",
                                "username": "jDoe",
                                "address" :  ".....",
                                "country": "US",
                                "city" :  "Chicago",
                                "postal_code": "12345",
                                "password" :  "admin!@#",
                                "password_confirmation" :  "admin!@#"
                            }
                        }
                    }
                },
                "responses": {
                    "default": {
                        "description": "Generic response"
                    }
                }
            }
        },
        "/close-my-account": {
            "get": {
                "tags": [
                    "Profile"
                ],
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "responses": {
                    "default": {
                        "description": "Generic response"
                    }
                }
            }
        },
        "/update-banner": {
            "post": {
                "tags": [
                    "Profile"
                ],
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "requestBody": {
                    "description": "Your request body description",
                    "required": true,
                    "content": {
                        "multipart/form-data": {
                            "schema": {
                                "type": "object",
                                "properties": {
                                    "cover": {
                                        "type": "string",
                                        "format": "binary",
                                        "description": "The image file to upload"
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "default": {
                        "description": "Generic response"
                    }
                }
            }
        },
        "/users/search": {
            "post": {
                "tags": [
                    "Users"
                ],
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "requestBody": {
                    "description": "Your request body description",
                    "required": true,
                    "content": {
                        "application/json": {
                            "example": {
                                "search" : "Maya"
                            }
                        }
                    }
                },
                "responses": {
                    "default": {
                        "description": "Generic response"
                    }
                }
            }
        },
        "/chat/channels": {
            "post": {
                "tags": [
                    "Chat"
                ],
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "requestBody": {
                    "description": "Your request body description",
                    "required": true,
                    "content": {
                        "application/json": {
                            "example": {
                                "search" : "Maya"
                            }
                        }
                    }
                },
                "responses": {
                    "default": {
                        "description": "Generic response"
                    }
                }
            }
        },
        "/chat/messages": {
            "post": {
                "tags": [
                    "Chat"
                ],
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "requestBody": {
                    "description": "Your request body description",
                    "required": true,
                    "content": {
                        "application/json": {
                            "example": {
                                "channel_id" : "49209ef9-13b7-483f-9253-6f910d3cd4b4"
                            }
                        }
                    }
                },
                "responses": {
                    "default": {
                        "description": "Generic response"
                    }
                }
            }
        }
    }
}
